# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_aafcqgissoiltool.ui'
#
# Created: Wed Mar 19 14:01:33 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AafcQgisSoilTool(object):
    def setupUi(self, AafcQgisSoilTool):
        AafcQgisSoilTool.setObjectName(_fromUtf8("AafcQgisSoilTool"))
        AafcQgisSoilTool.resize(697, 893)
        self.gridLayout = QtGui.QGridLayout(AafcQgisSoilTool)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(AafcQgisSoilTool)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabs = QtGui.QTabWidget(AafcQgisSoilTool)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.button_loadConfigFile = QtGui.QPushButton(self.tab_config)
        self.button_loadConfigFile.setGeometry(QtCore.QRect(390, 730, 131, 32))
        self.button_loadConfigFile.setObjectName(_fromUtf8("button_loadConfigFile"))
        self.button_upDateConfigFile = QtGui.QPushButton(self.tab_config)
        self.button_upDateConfigFile.setGeometry(QtCore.QRect(520, 730, 141, 32))
        self.button_upDateConfigFile.setObjectName(_fromUtf8("button_upDateConfigFile"))
        self.groupBox = QtGui.QGroupBox(self.tab_config)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 641, 51))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit_existingSoilDbPath = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_existingSoilDbPath.setGeometry(QtCore.QRect(120, 20, 491, 21))
        self.lineEdit_existingSoilDbPath.setObjectName(_fromUtf8("lineEdit_existingSoilDbPath"))
        self.button_existingSoilDbPath = QtGui.QPushButton(self.groupBox)
        self.button_existingSoilDbPath.setGeometry(QtCore.QRect(10, 20, 101, 32))
        self.button_existingSoilDbPath.setObjectName(_fromUtf8("button_existingSoilDbPath"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_config)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 591, 201))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 62, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_sqliteDbName = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_sqliteDbName.setGeometry(QtCore.QRect(110, 30, 191, 21))
        self.lineEdit_sqliteDbName.setObjectName(_fromUtf8("lineEdit_sqliteDbName"))
        self.lineEdit_cmpDbfPath = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_cmpDbfPath.setGeometry(QtCore.QRect(100, 70, 481, 21))
        self.lineEdit_cmpDbfPath.setObjectName(_fromUtf8("lineEdit_cmpDbfPath"))
        self.button_slfDbfPath = QtGui.QPushButton(self.groupBox_2)
        self.button_slfDbfPath.setGeometry(QtCore.QRect(3, 146, 83, 32))
        self.button_slfDbfPath.setAutoDefault(True)
        self.button_slfDbfPath.setObjectName(_fromUtf8("button_slfDbfPath"))
        self.lineEdit_snfDbfPath = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_snfDbfPath.setGeometry(QtCore.QRect(102, 104, 567, 21))
        self.lineEdit_snfDbfPath.setObjectName(_fromUtf8("lineEdit_snfDbfPath"))
        self.lineEdit_slfDbfPath = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_slfDbfPath.setGeometry(QtCore.QRect(100, 150, 572, 21))
        self.lineEdit_slfDbfPath.setObjectName(_fromUtf8("lineEdit_slfDbfPath"))
        self.button_cmpDbfPath = QtGui.QPushButton(self.groupBox_2)
        self.button_cmpDbfPath.setGeometry(QtCore.QRect(0, 60, 95, 32))
        self.button_cmpDbfPath.setAutoDefault(True)
        self.button_cmpDbfPath.setObjectName(_fromUtf8("button_cmpDbfPath"))
        self.button_snfDbfPath = QtGui.QPushButton(self.groupBox_2)
        self.button_snfDbfPath.setGeometry(QtCore.QRect(0, 100, 88, 32))
        self.button_snfDbfPath.setAutoDefault(True)
        self.button_snfDbfPath.setObjectName(_fromUtf8("button_snfDbfPath"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_config)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 320, 621, 201))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_dbSlcIdKey = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dbSlcIdKey.setGeometry(QtCore.QRect(260, 30, 321, 21))
        self.lineEdit_dbSlcIdKey.setObjectName(_fromUtf8("lineEdit_dbSlcIdKey"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 191, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_dbCmpKey = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dbCmpKey.setGeometry(QtCore.QRect(260, 60, 321, 21))
        self.lineEdit_dbCmpKey.setObjectName(_fromUtf8("lineEdit_dbCmpKey"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 191, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_dbSoilKey = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dbSoilKey.setGeometry(QtCore.QRect(260, 100, 321, 21))
        self.lineEdit_dbSoilKey.setObjectName(_fromUtf8("lineEdit_dbSoilKey"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 171, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_dbPercentKey = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dbPercentKey.setGeometry(QtCore.QRect(260, 140, 321, 21))
        self.lineEdit_dbPercentKey.setObjectName(_fromUtf8("lineEdit_dbPercentKey"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 211, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_dbLayerNumberKey = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dbLayerNumberKey.setGeometry(QtCore.QRect(260, 170, 321, 21))
        self.lineEdit_dbLayerNumberKey.setObjectName(_fromUtf8("lineEdit_dbLayerNumberKey"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_config)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 540, 401, 131))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.cb_userLandusePreference = QtGui.QComboBox(self.groupBox_4)
        self.cb_userLandusePreference.setGeometry(QtCore.QRect(210, 30, 111, 26))
        self.cb_userLandusePreference.setObjectName(_fromUtf8("cb_userLandusePreference"))
        self.cb_userLandusePreference.addItem(_fromUtf8(""))
        self.cb_userLandusePreference.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 161, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_csvFilePrefix = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_csvFilePrefix.setGeometry(QtCore.QRect(210, 60, 113, 21))
        self.lineEdit_csvFilePrefix.setObjectName(_fromUtf8("lineEdit_csvFilePrefix"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cb_userLayerNumber = QtGui.QComboBox(self.groupBox_4)
        self.cb_userLayerNumber.setGeometry(QtCore.QRect(210, 90, 111, 26))
        self.cb_userLayerNumber.setObjectName(_fromUtf8("cb_userLayerNumber"))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.cb_userLayerNumber.addItem(_fromUtf8(""))
        self.rb_useExistingSoilDb = QtGui.QRadioButton(self.tab_config)
        self.rb_useExistingSoilDb.setGeometry(QtCore.QRect(10, 10, 251, 20))
        self.rb_useExistingSoilDb.setChecked(True)
        self.rb_useExistingSoilDb.setObjectName(_fromUtf8("rb_useExistingSoilDb"))
        self.tabs.addTab(self.tab_config, _fromUtf8(""))
        self.tab_help = QtGui.QWidget()
        self.tab_help.setObjectName(_fromUtf8("tab_help"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_help)
        self.textBrowser.setGeometry(QtCore.QRect(20, 0, 601, 161))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabs.addTab(self.tab_help, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabs)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)

        self.retranslateUi(AafcQgisSoilTool)
        self.tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_cmpDbfPath, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_cmpDbfPath.update)
        QtCore.QMetaObject.connectSlotsByName(AafcQgisSoilTool)

    def retranslateUi(self, AafcQgisSoilTool):
        AafcQgisSoilTool.setWindowTitle(_translate("AafcQgisSoilTool", "AafcQgisSoilTool", None))
        self.button_loadConfigFile.setText(_translate("AafcQgisSoilTool", "Load Config File", None))
        self.button_upDateConfigFile.setText(_translate("AafcQgisSoilTool", "Update Config File", None))
        self.groupBox.setTitle(_translate("AafcQgisSoilTool", "Use Existing Soil Database", None))
        self.lineEdit_existingSoilDbPath.setText(_translate("AafcQgisSoilTool", "path to existing spatialite database", None))
        self.button_existingSoilDbPath.setText(_translate("AafcQgisSoilTool", "db path", None))
        self.groupBox_2.setTitle(_translate("AafcQgisSoilTool", "Create New Soil Database", None))
        self.label_2.setText(_translate("AafcQgisSoilTool", "Db Name", None))
        self.lineEdit_sqliteDbName.setText(_translate("AafcQgisSoilTool", "soilDb", None))
        self.lineEdit_cmpDbfPath.setText(_translate("AafcQgisSoilTool", "path to cmp dbf", None))
        self.button_slfDbfPath.setText(_translate("AafcQgisSoilTool", "slf dbf", None))
        self.lineEdit_snfDbfPath.setText(_translate("AafcQgisSoilTool", "path to snf dbf", None))
        self.lineEdit_slfDbfPath.setText(_translate("AafcQgisSoilTool", "path to slf dbf path", None))
        self.button_cmpDbfPath.setText(_translate("AafcQgisSoilTool", "cmp dbf", None))
        self.button_snfDbfPath.setText(_translate("AafcQgisSoilTool", "snf dbf", None))
        self.groupBox_3.setTitle(_translate("AafcQgisSoilTool", "Database Columns", None))
        self.label_3.setText(_translate("AafcQgisSoilTool", "Cmp table SLC Id Column", None))
        self.lineEdit_dbSlcIdKey.setText(_translate("AafcQgisSoilTool", "sl", None))
        self.label_4.setText(_translate("AafcQgisSoilTool", "Cmp table component column", None))
        self.lineEdit_dbCmpKey.setText(_translate("AafcQgisSoilTool", "cmp", None))
        self.label_5.setText(_translate("AafcQgisSoilTool", "Soilkey column to join tables", None))
        self.lineEdit_dbSoilKey.setText(_translate("AafcQgisSoilTool", "soilkey", None))
        self.label_6.setText(_translate("AafcQgisSoilTool", "Cmp percent column", None))
        self.lineEdit_dbPercentKey.setText(_translate("AafcQgisSoilTool", "percent", None))
        self.label_9.setText(_translate("AafcQgisSoilTool", "SLF Table Layer number column", None))
        self.lineEdit_dbLayerNumberKey.setText(_translate("AafcQgisSoilTool", "layer_no", None))
        self.groupBox_4.setTitle(_translate("AafcQgisSoilTool", "User Perferences", None))
        self.cb_userLandusePreference.setItemText(0, _translate("AafcQgisSoilTool", "N", None))
        self.cb_userLandusePreference.setItemText(1, _translate("AafcQgisSoilTool", "A", None))
        self.label_7.setText(_translate("AafcQgisSoilTool", "SNF Landuse Preference", None))
        self.label_8.setText(_translate("AafcQgisSoilTool", "CSV file prefix", None))
        self.lineEdit_csvFilePrefix.setText(_translate("AafcQgisSoilTool", "calculated", None))
        self.label_10.setText(_translate("AafcQgisSoilTool", "SLF layer number", None))
        self.cb_userLayerNumber.setItemText(0, _translate("AafcQgisSoilTool", "1", None))
        self.cb_userLayerNumber.setItemText(1, _translate("AafcQgisSoilTool", "2", None))
        self.cb_userLayerNumber.setItemText(2, _translate("AafcQgisSoilTool", "3", None))
        self.cb_userLayerNumber.setItemText(3, _translate("AafcQgisSoilTool", "4", None))
        self.cb_userLayerNumber.setItemText(4, _translate("AafcQgisSoilTool", "5", None))
        self.cb_userLayerNumber.setItemText(5, _translate("AafcQgisSoilTool", "6", None))
        self.cb_userLayerNumber.setItemText(6, _translate("AafcQgisSoilTool", "7", None))
        self.cb_userLayerNumber.setItemText(7, _translate("AafcQgisSoilTool", "8", None))
        self.cb_userLayerNumber.setItemText(8, _translate("AafcQgisSoilTool", "9", None))
        self.cb_userLayerNumber.setItemText(9, _translate("AafcQgisSoilTool", "10", None))
        self.cb_userLayerNumber.setItemText(10, _translate("AafcQgisSoilTool", "New Item", None))
        self.rb_useExistingSoilDb.setText(_translate("AafcQgisSoilTool", "Use Existing Spatialite Soil Database", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_config), _translate("AafcQgisSoilTool", "Configuration", None))
        self.textBrowser.setHtml(_translate("AafcQgisSoilTool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">help will go here</p></body></html>", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_help), _translate("AafcQgisSoilTool", "Help", None))

